//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaBot.Resources.CanteenNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CanteenNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanteenNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MensaBot.Resources.CanteenNames.CanteenNames", typeof(CanteenNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ce.
        /// </summary>
        internal static string canteen_Name_Cellar_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Cellar_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cellar.
        /// </summary>
        internal static string canteen_Name_Cellar_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Cellar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kellercafe.
        /// </summary>
        internal static string canteen_Name_Cellar_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Cellar_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cellar_cafe.
        /// </summary>
        internal static string canteen_Name_Cellar_3 {
            get {
                return ResourceManager.GetString("canteen_Name_Cellar_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        internal static string canteen_Name_Halberstadt_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Halberstadt_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to halberstadt.
        /// </summary>
        internal static string canteen_Name_Halberstadt_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Halberstadt_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to halber.
        /// </summary>
        internal static string canteen_Name_Halberstadt_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Halberstadt_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string canteen_Name_Herrenkrug_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Herrenkrug_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herrenkrug.
        /// </summary>
        internal static string canteen_Name_Herrenkrug_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Herrenkrug_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krug.
        /// </summary>
        internal static string canteen_Name_Herrenkrug_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Herrenkrug_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herren_krug.
        /// </summary>
        internal static string canteen_Name_Herrenkrug_3 {
            get {
                return ResourceManager.GetString("canteen_Name_Herrenkrug_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campus_lower.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen_lower.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_3 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main_floor.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_4 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower_hall.
        /// </summary>
        internal static string canteen_Name_Lower_Hall_5 {
            get {
                return ResourceManager.GetString("canteen_Name_Lower_Hall_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string canteen_Name_LowerUpper_0 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uni.
        /// </summary>
        internal static string canteen_Name_LowerUpper_1 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campus.
        /// </summary>
        internal static string canteen_Name_LowerUpper_2 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower&amp;upper.
        /// </summary>
        internal static string canteen_Name_LowerUpper_3 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper&amp;lower.
        /// </summary>
        internal static string canteen_Name_LowerUpper_4 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uni_campus.
        /// </summary>
        internal static string canteen_Name_LowerUpper_5 {
            get {
                return ResourceManager.GetString("canteen_Name_LowerUpper_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string canteen_Name_Stendal_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Stendal_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stendal.
        /// </summary>
        internal static string canteen_Name_Stendal_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Stendal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campus_upper.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen_upper.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_3 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper_floor.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_4 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper_hall.
        /// </summary>
        internal static string canteen_Name_Upper_Hall_5 {
            get {
                return ResourceManager.GetString("canteen_Name_Upper_Hall_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w.
        /// </summary>
        internal static string canteen_Name_Wernigerode_0 {
            get {
                return ResourceManager.GetString("canteen_Name_Wernigerode_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wernigerode.
        /// </summary>
        internal static string canteen_Name_Wernigerode_1 {
            get {
                return ResourceManager.GetString("canteen_Name_Wernigerode_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rode.
        /// </summary>
        internal static string canteen_Name_Wernigerode_2 {
            get {
                return ResourceManager.GetString("canteen_Name_Wernigerode_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wernigerode.
        /// </summary>
        internal static string canteen_Name_Wernigerode_3 {
            get {
                return ResourceManager.GetString("canteen_Name_Wernigerode_3", resourceCulture);
            }
        }
    }
}
