//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MensaBot.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added default canteen..
        /// </summary>
        internal static string add_canteen {
            get {
                return ResourceManager.GetString("add_canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add default canteen..
        /// </summary>
        internal static string add_canteen_failed {
            get {
                return ResourceManager.GetString("add_canteen_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added language&quot;.
        /// </summary>
        internal static string add_language {
            get {
                return ResourceManager.GetString("add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add language.
        /// </summary>
        internal static string add_language_failed {
            get {
                return ResourceManager.GetString("add_language_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added tags to ignore list:.
        /// </summary>
        internal static string add_tags {
            get {
                return ResourceManager.GetString("add_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add tags..
        /// </summary>
        internal static string add_tags_failed {
            get {
                return ResourceManager.GetString("add_tags_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen.
        /// </summary>
        internal static string canteen {
            get {
                return ResourceManager.GetString("canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /canteen, /menu, /nosh, /eat ....
        /// </summary>
        internal static string canteen_command_examples {
            get {
                return ResourceManager.GetString("canteen_command_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [canteencommand].
        /// </summary>
        internal static string canteen_command_tag {
            get {
                return ResourceManager.GetString("canteen_command_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [date].
        /// </summary>
        internal static string canteen_date_tag {
            get {
                return ResourceManager.GetString("canteen_date_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [canteencommand] [canteenname] [date].
        /// </summary>
        internal static string canteen_explained {
            get {
                return ResourceManager.GetString("canteen_explained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen name.
        /// </summary>
        internal static string canteen_name {
            get {
                return ResourceManager.GetString("canteen_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [canteenname].
        /// </summary>
        internal static string canteen_name_tag {
            get {
                return ResourceManager.GetString("canteen_name_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find canteen with name.
        /// </summary>
        internal static string canteen_not_found {
            get {
                return ResourceManager.GetString("canteen_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help.
        /// </summary>
        internal static string command_help {
            get {
                return ResourceManager.GetString("command_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for help..
        /// </summary>
        internal static string command_help_exit {
            get {
                return ResourceManager.GetString("command_help_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string command_help_intro {
            get {
                return ResourceManager.GetString("command_help_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today, tomorrow, the_day_after_tomorrow.
        /// </summary>
        internal static string date_examples {
            get {
                return ResourceManager.GetString("date_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find date with name.
        /// </summary>
        internal static string date_not_found {
            get {
                return ResourceManager.GetString("date_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed default canteen, if exists..
        /// </summary>
        internal static string deleted_canteen {
            get {
                return ResourceManager.GetString("deleted_canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed filter, if exists..
        /// </summary>
        internal static string deleted_filter {
            get {
                return ResourceManager.GetString("deleted_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to load information about.
        /// </summary>
        internal static string fail_to_load_information {
            get {
                return ResourceManager.GetString("fail_to_load_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry 💔!.
        /// </summary>
        internal static string failed_sorry {
            get {
                return ResourceManager.GetString("failed_sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alcohol.
        /// </summary>
        internal static string food_tag_alcohol {
            get {
                return ResourceManager.GetString("food_tag_alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beef.
        /// </summary>
        internal static string food_tag_beef {
            get {
                return ResourceManager.GetString("food_tag_beef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bio.
        /// </summary>
        internal static string food_tag_bio {
            get {
                return ResourceManager.GetString("food_tag_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chicken.
        /// </summary>
        internal static string food_tag_chicken {
            get {
                return ResourceManager.GetString("food_tag_chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fish.
        /// </summary>
        internal static string food_tag_fish {
            get {
                return ResourceManager.GetString("food_tag_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to garlic.
        /// </summary>
        internal static string food_tag_garlic {
            get {
                return ResourceManager.GetString("food_tag_garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hogget.
        /// </summary>
        internal static string food_tag_hogget {
            get {
                return ResourceManager.GetString("food_tag_hogget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pork.
        /// </summary>
        internal static string food_tag_pork {
            get {
                return ResourceManager.GetString("food_tag_pork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soup.
        /// </summary>
        internal static string food_tag_soup {
            get {
                return ResourceManager.GetString("food_tag_soup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vegan.
        /// </summary>
        internal static string food_tag_vegan {
            get {
                return ResourceManager.GetString("food_tag_vegan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vegetarian.
        /// </summary>
        internal static string food_tag_vegetarian {
            get {
                return ResourceManager.GetString("food_tag_vegetarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vension.
        /// </summary>
        internal static string food_tag_vension {
            get {
                return ResourceManager.GetString("food_tag_vension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vital.
        /// </summary>
        internal static string food_tag_vital {
            get {
                return ResourceManager.GetString("food_tag_vital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get a description for emojis.
        /// </summary>
        internal static string help_emoji_description {
            get {
                return ResourceManager.GetString("help_emoji_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /list canteens - Shows all canteens and their shortcuts..
        /// </summary>
        internal static string list_canteen_description {
            get {
                return ResourceManager.GetString("list_canteen_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all canteens and their shortcuts:.
        /// </summary>
        internal static string list_of_canteens {
            get {
                return ResourceManager.GetString("list_of_canteens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no english translation available.
        /// </summary>
        internal static string no_english_available {
            get {
                return ResourceManager.GetString("no_english_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not play ping pong..
        /// </summary>
        internal static string not_play_ping_pong {
            get {
                return ResourceManager.GetString("not_play_ping_pong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        internal static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping! 🏓.
        /// </summary>
        internal static string ping {
            get {
                return ResourceManager.GetString("ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add.
        /// </summary>
        internal static string please_add {
            get {
                return ResourceManager.GetString("please_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note.
        /// </summary>
        internal static string please_note {
            get {
                return ResourceManager.GetString("please_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pong! 🏓.
        /// </summary>
        internal static string pong {
            get {
                return ResourceManager.GetString("pong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not an official bot from Studentenwerk Magdeburg..
        /// </summary>
        internal static string reference_1 {
            get {
                return ResourceManager.GetString("reference_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot uses public informations from their website..
        /// </summary>
        internal static string reference_2 {
            get {
                return ResourceManager.GetString("reference_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help for /remove.
        /// </summary>
        internal static string remove_help {
            get {
                return ResourceManager.GetString("remove_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use: /remove canteen to delte information about the default canteen..
        /// </summary>
        internal static string remove_help_canteen {
            get {
                return ResourceManager.GetString("remove_help_canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use: /remove filter to delete all filter settings..
        /// </summary>
        internal static string remove_help_filter {
            get {
                return ResourceManager.GetString("remove_help_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed all data from you!.
        /// </summary>
        internal static string removed_all_data {
            get {
                return ResourceManager.GetString("removed_all_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove data from you..
        /// </summary>
        internal static string removed_all_data_failed {
            get {
                return ResourceManager.GetString("removed_all_data_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This did not work. Use: /set help.
        /// </summary>
        internal static string set_fail {
            get {
                return ResourceManager.GetString("set_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help for /set.
        /// </summary>
        internal static string set_help {
            get {
                return ResourceManager.GetString("set_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use: /set canteen [canteenname] to update the default mensa..
        /// </summary>
        internal static string set_help_canteen {
            get {
                return ResourceManager.GetString("set_help_canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use: /set filter [filterA],[filterB].... to ignore meals with given tags, e.g. /set filter vegan,pork....
        /// </summary>
        internal static string set_help_filter {
            get {
                return ResourceManager.GetString("set_help_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you to solve this problem..
        /// </summary>
        internal static string start_exit {
            get {
                return ResourceManager.GetString("start_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungry? 😋.
        /// </summary>
        internal static string start_intro {
            get {
                return ResourceManager.GetString("start_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string start_welcome {
            get {
                return ResourceManager.GetString("start_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command!.
        /// </summary>
        internal static string unknown_command {
            get {
                return ResourceManager.GetString("unknown_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please do usefull things, otherwise you still will be hungry..
        /// </summary>
        internal static string unknown_command_joke_msg {
            get {
                return ResourceManager.GetString("unknown_command_joke_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown language..
        /// </summary>
        internal static string unknown_language {
            get {
                return ResourceManager.GetString("unknown_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this syntax.
        /// </summary>
        internal static string use_syntax {
            get {
                return ResourceManager.GetString("use_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean: /remove canteen or /remove mensa.
        /// </summary>
        internal static string wrong_param_remove_canteen {
            get {
                return ResourceManager.GetString("wrong_param_remove_canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean /remove filter?.
        /// </summary>
        internal static string wrong_param_remove_filter {
            get {
                return ResourceManager.GetString("wrong_param_remove_filter", resourceCulture);
            }
        }
    }
}
