//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensaBot.Resources.CanteenCommand {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CanteenCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanteenCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MensaBot.Resources.CanteenCommand.CanteenCommand", typeof(CanteenCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen.
        /// </summary>
        internal static string canteen_0 {
            get {
                return ResourceManager.GetString("canteen_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nosh.
        /// </summary>
        internal static string canteen_1 {
            get {
                return ResourceManager.GetString("canteen_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eat.
        /// </summary>
        internal static string canteen_2 {
            get {
                return ResourceManager.GetString("canteen_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        internal static string canteen_3 {
            get {
                return ResourceManager.GetString("canteen_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to food.
        /// </summary>
        internal static string canteen_4 {
            get {
                return ResourceManager.GetString("canteen_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hungry.
        /// </summary>
        internal static string canteen_5 {
            get {
                return ResourceManager.GetString("canteen_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mensa.
        /// </summary>
        internal static string canteen_6 {
            get {
                return ResourceManager.GetString("canteen_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_command_9001.
        /// </summary>
        internal static string canteen_7 {
            get {
                return ResourceManager.GetString("canteen_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_command_9001.
        /// </summary>
        internal static string canteen_8 {
            get {
                return ResourceManager.GetString("canteen_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_command_9001.
        /// </summary>
        internal static string canteen_9 {
            get {
                return ResourceManager.GetString("canteen_9", resourceCulture);
            }
        }
    }
}
